### ISSUE TITLE
create a security process

### ISSUE THREAD

**Issue by philips** [etcd-io/maintainers#1]
etcd doesn't have a security disclosure and release process. Creating such a process is necessary to graduate as a CNCF project.

Things that we need:

- [x] security team to handle incoming disclosures (2-3 people)
- [x] security disclosure mailing list (e.g. security@etcd.io) 
- [x] documented process for getting CVE ids, making releases, and announcing releases (e.g. [Kubernetes process](https://github.com/kubernetes/security/blob/master/security-release-process.md))

I am willing to give a run down of the Kubernetes process to the etcd team but I don't have time to be a member of the security team or create the docs.

**Comment by philips** [comment]
cc @xiang90 @gyuho @jpbetz @hexfusion @heyitsanthony @fanminshi @mitake

**Comment by philips** [comment]
Does anyone on the @etcd-io/maintainers-etcd have time to handle this? The mailing list is ready to go?

**Comment by spzala** [comment]
@philips hello, I am not a security SME but I can help out with tasks you have mentioned in the description like creating the process docs, watching incoming security vulnerabilities, release work etc. as part of the security team if that helps. Thanks!

**Comment by philips** [comment]
@spzala that would be great! we could probably borrow heavily from https://github.com/kubernetes/security but also make something lighter given the much smaller scope of etcd.

**Comment by spzala** [comment]
@philips thanks and yes, I totally agree! While we work on making the team, I will start working on creating process/doc and have something ready for review in next few days. Thanks!

**Comment by spzala** [comment]
@philips I have created a lighter version of Kubernetes process with changes I felt needed for etcd. I have also referred to a smaller project like envoy. I believe we don't need a separate repo like Kubernetes, so I have created a security folder. Please take a look when you get a chance :-) Thanks!

**Comment by spzala** [comment]
@philips hello, I guess we can close this issue now? Thanks!

**Comment by philips** [comment]
yea, closing.

**Comment by spzala** [comment]
:-) Thanks @philips !!
