### ISSUE TITLE
jepsen correctness audit

### ISSUE THREAD

**Issue by philips** [etcd-io/maintainers#10]
Around September or November the etcd project will engage with @aphyr to do a correctness audit of the project. Further, @mitake and @gyuho have volunteered to lead. 

Use this issue for updates on the project plan, etc.

xref https://github.com/etcd-io/maintainers/issues/3

**Comment by philips** [comment]
@caniszczyk any updates on when the engagement might start?

**Comment by mitake** [comment]
@philips @gyuho can we talk about this topic during KubeCon?

**Comment by philips** [comment]
Pingd @gyuho about this today.

**Comment by philips** [comment]
The audit is now underway with @mitake @gyuho involved and all etcd maintainers subscribed to updates.

**Comment by leoluk** [comment]
Any updates on how the audit is going?

**Comment by philips** [comment]
everything is going well, wrapping up. We hope to have results up by end of Feb.

**Comment by philips** [comment]
Done! https://etcd.io/blog/jepsen-343-results/

closing.
