### ISSUE TITLE
etcd mailing list changes

### ISSUE THREAD

**Issue by spzala** [etcd-io/maintainers#14]
Thought of couple of changes that we may want to consider with etcd mailing list
* Currently the `etcd-dev` google group is `Shared privately` - we should share it publicly similar to Kubernetes, Kubernetes SIGs and other CNCF projects like Prometheus
* We only have `etcd-dev` group - this is a minor but thought would mention it. We don't have a very busy activities in the ML but wondering if we should think about creating etcd-user group similar to other projects or clearly describe that it's not for dev only. Renaming it to make it more generic is an option if we want to keep a single ML only but since people are familiar with it for long time I guess it might not be a good idea.

**Comment by philips** [comment]
1. sharing privately IIRC was just about showing up in the google group search index. Is that right? I am fine turning it publicly.

2. I am fine renaming the group but I don't think there is anyway to rename it without breaking links everywhere.

**Comment by spzala** [comment]
Thanks @philips !! 
Agree, renaming probably is not going to be easy but that's something that we can discuss more and see if anyone comes up with a better idea. 
I don't think I have access to change settings to public. I am also not familiar with original discussion around sharing it privately but I am sure that made more sense in the past.

**Comment by philips** [comment]
@spzala can you subscribe with your email listed in https://github.com/etcd-io/etcd/blob/master/MAINTAINERS and I will make you an admin of the google group.

**Comment by spzala** [comment]
@philips hello, I have associated that email with gmail and just joined the etcd-dev group using that email. I really hope that should work. Can you please verify and let me know. Thank you!!

**Comment by philips** [comment]
@spzala you are now an owner.

**Comment by spzala** [comment]
@philips Thank you!! I verified it. I will be working on making group public during the weekdays when team members are around in case needed any quick discussion :-). Have a great weekend! Thanks!

**Comment by spzala** [comment]
@philips hi, I have changed the settings to make it public and it is now consistent with other projects/SIGs. If you get a chance, please verify. I have already verified it from non-work computer with and without gmail logging. Thanks! 

With an un-subscribed gmail logging:
![image](https://user-images.githubusercontent.com/6462877/65554741-705e6180-def8-11e9-9650-24120801cb66.png)

Without logging:
![image](https://user-images.githubusercontent.com/6462877/65554792-8f5cf380-def8-11e9-9935-83e26b26cd44.png)

**Comment by spzala** [comment]
Also, as we discussed renaming won't be easy and probably not a good idea. So I will close the issue with this setting change. Thanks!

**Comment by philips** [comment]
sounds good, thanks Sahdev

**Comment by spzala** [comment]
Thank you @philips !!
