### ISSUE TITLE
Third-party security audit

### ISSUE THREAD

**Issue by philips** [etcd-io/maintainers#18]
A security audit is needed for etcd to reach the CNCF Graduated project status.

Rough todo from the process Kubernetes followed:

- [x] Identify a lead for the project
- [x] Identify 1-3 maintainers to help guide the auditors
- [x] Maintainer files a [CNCF Service Desk ticket](https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1/group/1/create/8) to request a security audit
- [ ] Wait
- [ ] Work with security audit team
- [ ] Work with CNCF to publish results

cc @spzala

**Comment by gyuho** [comment]
I will be in the loop.

**Comment by xiang90** [comment]
i can help.

**Comment by xiang90** [comment]
assigned to Guyho and myself.

**Comment by philips** [comment]
thanks xiang. It would be great to get a few dates together that would work
for people to start so the CNCF can start the contract drafts.

**Comment by gyuho** [comment]
Talked with @spzala. Think he's working on creating a CNCF service desk ticket. Can you give us an update?

**Comment by spzala** [comment]
@gyuho hi, I worked with Ihor and got an account created for the CNCF service desk to create a ticket. My account was good when it was created few days back but somehow not letting me log-in anymore (it recognizes my email and let me reset password but not letting me log-in). I have sent an email about this issue. I will share a draft of application with everyone real soon. Thanks!

**Comment by spzala** [comment]
I have just shared a draft with our small group working on this issue for an initial review/thoughts, please take a look. I will share with all the maintainers after you take a quick look. Thanks!

**Comment by spzala** [comment]
@xiang90 @gyuho thanks for your quick review of the application draft and resolving my comments related to dates. I have shared it with all the maintainers now for their review. Thanks!

**Comment by spzala** [comment]
@gyuho hi, we are good with the proposal content per the review feedback. I think the only thing remained now is the third party security audit. Thanks!

**Comment by caniszczyk** [comment]
I am reaching out to schedule a security audit, please let me know who from the etcd team will be available to help with it.

**Comment by spzala** [comment]
@caniszczyk thanks! Please consider @xiang90 @gyuho and myself for now. Also please keep @philips in the loop. I believe we can change one or two individuals here if needed due to schedule conflict/travel etc? 
/cc 
@xiang90 @gyuho @philips - hope this is fine per earlier discussion. Should we ask Mitake as well? Thanks!

**Comment by philips** [comment]
I think Mitake should be involved since he worked on some of the auth stuff
originally.

**Comment by spzala** [comment]
@philips thanks! Yes, sounds great. 
/cc
@mitake hi, I hope you would like to be a part of the team here :-). I will also ping you separately as GH notification can go unnoticed sometime. Thanks!

**Comment by mitake** [comment]
@spzala @philips sure, I'd like to participate to this :) I'll join to the assignee of this ticket.

**Comment by mitake** [comment]
It seems that I cannot update the assignee list of this issue. @xiang90 @gyuho could you include me?

**Comment by spzala** [comment]
@mitake :) awesome! Thanks!
/cc @caniszczyk

**Comment by caniszczyk** [comment]
etcd security audit agreement set, intros sent to kick things off

good luck!

**Comment by spzala** [comment]
Security audit results are now published - https://github.com/etcd-io/etcd/blob/master/security/SECURITY_AUDIT.pdf and announced by CNCF https://www.cncf.io/blog/2020/08/05/etcd-security-audit/ Thanks @caniszczyk @xiang90 @gyuho @philips @mitake and all the maintainers! Closing this issue.
