### ISSUE TITLE
Add license scanning via FOSSA

### ISSUE THREAD

**Issue by philips** [etcd-io/maintainers#4]
CNCF requires projects to have license scanning for projects: https://fossa.com

**Comment by philips** [comment]
Filed a service desk request for the license @caniszczyk.

**Comment by philips** [comment]
Still waiting on @caniszczyk.

**Comment by caniszczyk** [comment]
@philips it's self serve for maintainers to do it, I just need to know when it's enabled so I can transfer it to the CNCF org account for the enterprise plan we have.

Happy to do it but need admin on the etcd org/repo to install it

**Comment by philips** [comment]
@caniszczyk I gave you admin permissions via a new @etcd-io/cncf team. Go for it.

**Comment by philips** [comment]
@caniszczyk says this is on now, thanks Chris.
