### ISSUE TITLE
fast PR testing infrastructure

### ISSUE THREAD

**Issue by philips** [etcd-io/maintainers#5]
etcd has both semaphore and travis hooked up to PRs but is crazy slow. I waited for 10 minutes last night for a test to simply queue to run.

This disproportionately affects new contributors because they may not have the infrastructure to run the tests manually.

Potential solutions:

- Pay for Travis
- Use Prow from the Kubernetes project

cc @etcd-io/maintainers-etcd

**Comment by jingyih** [comment]
I just took a quick look. Each build triggers 11 test jobs. Each test takes about 4 to 15 min in general to finish. Travis runs 3 jobs concurrently. So all 11 tests of each build is probably going to take 30~40 min to finish. During peak time when tests for multiple builds are queued, waiting time could be hours.

**Comment by philips** [comment]
I filed a request with the CNCF service desk.

**Comment by philips** [comment]
Does anyone know why we have both Semaphore and Travis?

**Comment by xiang90** [comment]
@philips Travis was too slow for a full CI testing. And we were just trying to add more parallelism on CI to use both Travis and Semaphore.

**Comment by philips** [comment]
@caniszczyk said he can dig into more parallel builders for travis. Assigning to him.

**Comment by caniszczyk** [comment]
update: made the request to travis and you should get up to 10 concurrent runners within 24 hours, been a bit of an adventure due to the travis-ci.org vs travis-ci.com split, I will test before closing this though

I'm also exploring using Azure Pipelines for etcd as an option which may offer better performance

**Comment by philips** [comment]
great news Chris, thanks!

**Comment by jingyih** [comment]
@caniszczyk Hi Chris, today I created a PR, it looks like we still only get 3 concurrent jobs running in Travis CI. Could you help double check with Travis?

**Comment by philips** [comment]
I pinged the CNCF service desk request again today. FYI @caniszczyk

**Comment by philips** [comment]
@amye talked to Travis and it should be faster now, anyone have a PR that they can try it out on?

**Comment by jingyih** [comment]
I just triggered a new build, all 11 Travis CI tests are running in parallel!

**Comment by philips** [comment]
I think we are good on this, closing
