### ISSUE TITLE
etcd.io email aliases

### ISSUE THREAD

**Issue by philips** [etcd-io/maintainers#6]
It would be ideal to have a Gsuite setup with Google Groups to handle gcloud access control for the etcd-development and for various lists we need:

- [x] maintainers@etcd.io
- [x] maintainers-private@etcd.io
- [x] security@etcd.io

@lucperkins can you do this?

**Comment by philips** [comment]
also filed a service desk ticket. https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1/CNCFSD-204

**Comment by idvoretskyi** [comment]
@philips please unassign Luc and assign me. I'm working with the LF IT on this.

**Comment by spzala** [comment]
@philips @xiang90 A quick update - I just had a brief chat with Ihor. He will be checking out the progress on the work related to this issue and providing an update. Thanks, and thank you @idvoretskyi !!

**Comment by philips** [comment]
Alright, I have admin access now and created the groups.

maintainers-private is added to the other two lists.
