### ISSUE TITLE
etcd.io SEO problems

### ISSUE THREAD

**Issue by philips** [etcd-io/maintainers#8]
etcd.io isn't showing up highly in Google Indexes. We need to do a few corrections:

- [x] Remove readthedocs.io links xref https://github.com/etcd-io/etcd/pull/10744
- [x] Redirect coreos.com/etcd to etcd.io
- [x] Fix mobile site recommendations in the Google webmaster tools

**Comment by philips** [comment]
@gyuho I need your help on the readthedocs.io stuff.

**Comment by philips** [comment]
Removed mobile site recommendations as they were all for go.etcd.io which isn't a priority.

**Comment by gyuho** [comment]
@philips Sorry, I was out on vacation. Just removed https://etcd.readthedocs.io/en/latest/. And will work on migrating the old docs to the new doc website.

**Comment by philips** [comment]
Alright, all of the other sources of truth are down. Lets see how it goes....
