### ISSUE TITLE
security: try out new Github security tooling

### ISSUE THREAD

**Issue by philips** [etcd-io/maintainers#9]
It would be great to use the new Github security policy stuff instead of having to use a mailing list for disclosures! 

https://help.github.com/en/articles/adding-a-security-policy-to-your-repository

**Comment by philips** [comment]
I tried it out. It is good, we should create a policy, however it doesn't enable private disclosure via GH issues as I hoped.

**Comment by spzala** [comment]
@philips hello, I guess we can close this issue now? The etcd GH `Security` > `Policy` shows our SECURITY.md now. Thanks!

**Comment by philips** [comment]
yes

**Comment by spzala** [comment]
Thanks @philips !!
